# Generated by Django 6.0.5 on 2026-06-10 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('device_id', models.CharField(max_length=200, unique=True, verbose_name='device id')),
                ('os_name', models.IntegerField(choices=[(0, 'ios'), (1, 'android')], verbose_name='os name')),
                ('app_version', models.CharField(max_length=200, verbose_name='application version')),
                ('os_version', models.CharField(max_length=200, verbose_name='os version')),
                ('model', models.CharField(max_length=200, verbose_name='model')),
                ('language', models.IntegerField(choices=[(0, 'russian'), (1, 'english')], default=1, verbose_name='language')),
                ('firebase_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='firebase token')),
                ('auth_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to=settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL)),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
            },
        ),
    ]
