# Generated by Django 6.0.5 on 2026-06-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('code', models.IntegerField(verbose_name='code')),
                ('otp_token', models.CharField(max_length=32, verbose_name='token')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'sent'), (1, 'verified'), (2, 'used')], verbose_name='status')),
            ],
            options={
                'verbose_name': 'one-time password',
                'verbose_name_plural': 'one-time passwords',
            },
        ),
    ]
